---
registry:
  image: library/registry:2
  environment:
    STORAGE_PATH: /storage
  volumes:
    - "/opt/floating-dock/registry/storage:/storage"
postgres:
  image: postgres:9.5
  volumes:
    - "/opt/floating-dock/database:/var/lib/postgresql/data"
  environment:
    POSTGRES_PASSWORD: rails_db
    POSTGRES_USER: rails_db
app:
  image: "cloudfleet/floating-dock"
  links:
    - postgres
  env_file:
    - .env
  environment:
    DB_HOST: "postgres"
worker:
  image: "cloudfleet/floating-dock"
  command: rake jobs:work
  environment:
    DB_HOST: postgres
  env_file:
    - .env
  links:
    - postgres
nginx:
  image: "cloudfleet/nginx-registry-proxy"
  ports:
    - "443:443"
  links:
    - registry
    - app
  volumes:
    - "/etc/letsencrypt:/etc/letsencrypt"
    - "/root/security:/etc/nginx/external"
  environment:
    DH_SIZE: "512"
