---
registryaarch64:
  image: library/registry:2
  environment:
    STORAGE_PATH: /storage
  volumes:
    - "/opt/floating-dock/registry/storage:/storage"
    - "/root/security:/auth"
registryarmhf:
  image: library/registry:2
  environment:
    STORAGE_PATH: /storage
  volumes:
    - "/opt/floating-dock/registry/storage:/storage"
    - "/root/security:/auth"
postgres:
  image: postgres:9.5
  volumes:
    - "/opt/floating-dock/database:/var/lib/postgresql/data"
  environment:
    POSTGRES_PASSWORD: rails_db
    POSTGRES_USER: rails_db
app:
  image: "cloudfleet/floating-dock"
  links:
    - postgres
  env_file:
    - .env
  environment:
    DB_HOST: "postgres"
worker:
  image: "cloudfleet/floating-dock"
  command: "sh -c /bin/sh bundle exec rake jobs:work"
  environment:
    DB_HOST: postgres
  env_file:
    - .env
  links:
    - postgres
nginx:
  image: bradjonesllc/docker-nginx-letsencrypt
  ports:
    - "80:80"
    - "443:443"
  links:
    - app
    - registry
  environment:
    CERTS: marina.io,aarch64.registry.marina.io,armv7.registry.marina.io
    EMAIL: info@marina.io
  volumes:
    - "/opt/floating-dock/nginx/ssl:/etc/nginx/ssl"
    - "/opt/floating-dock/nginx/ssl/dhparam:/etc/ssl/dhparam"
    - "/opt/floating-dock/nginx/letsencrypt:/etc/letsencrypt"
    - "/opt/floating-dock/floating-dock-composition/nginx.conf:/etc/nginx/conf.d/ssl.conf"
