---
{% for arch in archs %}
registry{{arch}}:
  image: library/registry:2
  environment:
    STORAGE_PATH: /storage
    REGISTRY_AUTH_TOKEN_REALM: https://marina.io/jwt
    REGISTRY_AUTH_TOKEN_SERVICE: container_registry
    REGISTRY_AUTH_TOKEN_ISSUER: floating-dock
    REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /registry/auth/registry.crt
  volumes:
    - "/opt/floating-dock/registry{{arch}}/storage:/storage"
    - "/opt/floating-dock/registry/certs/registry.crt:/registry/auth/registry.crt"
{% endfor %}
postgres:
  image: postgres:9.5
  volumes:
    - "/opt/floating-dock/database:/var/lib/postgresql/data"
  environment:
    POSTGRES_PASSWORD: rails_db
    POSTGRES_USER: rails_db
app:
  image: "cloudfleet/floating-dock"
  links:
    - postgres
  env_file:
    - .env
  environment:
    DB_HOST: "postgres"
    DOCKER_REGISTRY_JWT_KEY: "/registry/auth/registry.key"
    ARCHS: {{','.join(archs)}}
  volumes:
    - "/opt/floating-dock/registry/certs/registry.key:/registry/auth/registry.key"
worker:
  image: "cloudfleet/floating-dock"
  command: "sh -c /bin/sh bundle exec rake jobs:work"
  environment:
    DB_HOST: postgres
  env_file:
    - .env
  links:
    - postgres
nginx:
  image: bradjonesllc/docker-nginx-letsencrypt
  ports:
    - "80:80"
    - "443:443"
  links:
    - app
    - registry
  environment:
    CERTS: {% for arch in archs %}{{arch}}.registry.marina.io,{% endfor %}marina.io
    EMAIL: info@marina.io
  volumes:
    - "/opt/floating-dock/nginx/ssl:/etc/nginx/ssl"
    - "/opt/floating-dock/nginx/ssl/dhparam:/etc/ssl/dhparam"
    - "/opt/floating-dock/nginx/letsencrypt:/etc/letsencrypt"
    - "/opt/floating-dock/floating-dock-composition/nginx.conf:/etc/nginx/conf.d/ssl.conf"
